### ISSUE TITLE
Bug: Snap Directory does not detect MetaMask even when a user is on v11 of Chrome / Firefox / Brave

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-directory#110]
We have received multiple reports of users not being able to install Snaps from the directory even though they are on version 11.0 of the extension in Chrome, Firefox, or Brave. We should try to reproduce this issue and see if there is a bug we are not aware of.

**Comment by bowensanders** [comment]
Looking into this now. 
I do know that if you go to the snaps directory before installing MM, that if you do not reload the snaps directory page, it does not detect MM install, and you need to reload the page to get it to work. I will try to find other instances.

**Comment by FrederikBolding** [comment]
This may be solved by https://github.com/MetaMask/snaps-directory/pull/114
