### ISSUE TITLE
Add empty state when users do not have installed snaps

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps-directory#115]
Add an empty state when users do not have installed snaps but use the "installed" filter.

**Comment by eriknson** [comment]
Figma: https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/MetaMask-Directory?type=design&node-id=645%3A27251&mode=design&t=FWooc10bJMHBeOzG-1

<img width="1521" alt="search-empty-state" src="https://github.com/MetaMask/snaps-directory/assets/34306844/3fb921f3-1555-4b9b-8915-fa2310900f5c">
