### ISSUE TITLE
Show available updates on index page

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps-directory#137]
When one or more snaps have available updates, we should show this somewhere on the index page (with a banner of some sort maybe).

**Comment by eriknson** [comment]
Design: https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=1%3A1314&mode=design&t=NFN2TDHHueRwpnLf-1

<img width="745" alt="directory-notifs" src="https://github.com/MetaMask/snaps-directory/assets/34306844/1b167432-2d81-4fbd-bbdf-33b57d09912e">
