### ISSUE TITLE
Segment event for clicking "Add to MetaMask" 

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-directory#149]
Clicking the "Add to MetaMask" button should log an event 

Adjacent question: is there an update button if the user can update the Snap?

**Comment by Mrtenz** [comment]
> Adjacent question: is there an update button if the user can update the Snap?

Yes. Should there be a separate event for this?

**Comment by Montoya** [comment]
> > Adjacent question: is there an update button if the user can update the Snap?
> 
> Yes. Should there be a separate event for this?

Yes
