### ISSUE TITLE
Borders on avatars in dark mode

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/snaps-directory#173]
In Chrome 117 on Mac Sonoma 14.0.  Some of the borders are observably light in dark mode, and a few seem to lose the light outline across the top and sides of the round svg making for a flattening effect on the edges of the otherwise round avatars.
 
![Screenshot 2023-10-20 at 4 01 46 PM](https://github.com/MetaMask/snaps-directory/assets/32695229/5b7f1327-15f6-4f90-a40a-872052f55cf4)

This is not as noticeable in light mode, with the exception with the filecoin image it seems to have a light pixels around the border in both display modes:
![Screenshot 2023-10-20 at 1 44 20 PM](https://github.com/MetaMask/snaps-directory/assets/32695229/b1a969ae-e5e2-422f-ba25-7194685b8c0a)

![Screenshot 2023-10-20 at 3 55 02 PM](https://github.com/MetaMask/snaps-directory/assets/32695229/818088b4-cd74-48fa-a3b3-452f4d839724)

**Comment by FrederikBolding** [comment]
Fixed in #223
