### ISSUE TITLE
Permissions on profile

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps-directory#22]
On the snaps details page we want to show a list of snap permissions.

**Comment by eriknson** [comment]
Permissions on profile
- Collapses under a "See More" button if container height > `350px`
- Description & permissions collapses individually on mobile viewports
- Permission / tooltip copy can be reviewed in another PR

<img width="1687" alt="permissions-on-profile" src="https://github.com/MetaMask/snaps-directory/assets/34306844/1a05c359-1fa6-48ea-b225-a5415ccb403d">
