### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps-directory#25]

**Comment by eriknson** [comment]
Design: https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/MetaMask-Directory?type=design&node-id=739%3A49201&mode=design&t=ERj2VaQSrkMAv6m5-1

![directory-dark-mode](https://github.com/MetaMask/snaps-directory/assets/34306844/05c0f443-023c-41dc-86a9-c52a8f931b38)
