### ISSUE TITLE
Directory updates for the account snaps launch

### ISSUE THREAD

**Issue by eriknson** [MetaMask/snaps-directory#279]
- Category on start page with the title "Create an Ethereum account"
- Account Management Snaps legal disclaimer to the footer
- A warning state w/ tooltip for the `source code` metadata field

**Comment by eriknson** [comment]
I'll update their request to fit into the redesign in figma

**Comment by eriknson** [comment]
To communicate that some of the source code is private we're adding [this state](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=2963%3A73826&mode=design&t=bMUf29mZANG6y4Zm-1) to the source code metadata field

<img width="847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ff6b1169e5169612b1820432d2dafb8be569758/accounts-modal-metadata.png" alt="accounts-modal-metadata.png" />

**Comment by eriknson** [comment]
We're appending [this disclaimer](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=2425%3A129856&mode=design&t=bMUf29mZANG6y4Zm-1) to the footer on any account management profile:

> Experimental Beta
Account Management Snaps are released as part of an experimental beta release. You agree that you will only use one of these Snaps if you understand how it functions and how to use it, and you have fully read and understand all risk warnings and other disclosures made available by the Third Party Service provider relating to use of their Snap. You agree that Consensys is not responsible for any injury that you incur as a result of your use of this Snap.

> You will not be able to use your MetaMask Secret Recovery Phrase to recover accounts added through Account Management Snaps. If your account credentials are lost or compromised, MetaMask will not be able to help you. If the Snap or the associated dapp is hacked or ceases to function, you may not be able to access your account and the funds in your account.

<img width="1698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUhIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1547ba77794b3580db6f5bd86e5bca940eff7ce2/accounts-footer-directory.png" alt="accounts-footer-directory.png" />

**Comment by eriknson** [comment]
We're adding a category on the start page (as the first / top one)

<img width="1241" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW5IQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97592e78d6a3a4ef6275fc25f58fce6e02dbf9b1/accounts-category-directory.png" alt="accounts-category-directory.png" />

**Comment by eriknson** [comment]
Discussion on Slack: https://consensys.slack.com/archives/C05V3JXAYLW/p1705329238023969

**Comment by kenhkan** [comment]
From standup:
* Title: "Create an Ethereum account"
* Erik to fix SVG icon
