### ISSUE TITLE
Profile screenshots

### ISSUE THREAD

**Issue by eriknson** [MetaMask/snaps-directory#283]
Let's [make the profile visual](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=3011%3A72811&mode=design&t=bMUf29mZANG6y4Zm-1) by lettings snap developers add screenshots showcasing how it works

**Spec / requirements**
- 3 images (no less, no more)
- stored in the registry
- 16:9 aspect ratio
- exactly `960px` width, `540px` height

<img width="2358" alt="directory-screenshots" src="https://github.com/MetaMask/snaps-directory/assets/34306844/e54f8342-a600-4c8d-8d74-629625d1871d">
<img width="1651" alt="directory-screenshots-fullscreen" src="https://github.com/MetaMask/snaps-directory/assets/34306844/a934e1d4-0c9e-41cc-bb6a-70eb25be9ec5">

**Comment by eriknson** [comment]
Discussion about this issue: https://github.com/MetaMask/snaps/discussions/2095

**Comment by kenhkan** [comment]
From standup:
* Anyone interested can pick this up for implementation.

**Comment by kenhkan** [comment]
From sprint planning:
* Anyone can pick this up.
* Do we host it on Github Pages?
