### ISSUE TITLE
Implement localisation

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps-directory#314]
Now that we have a process set up for translations, we need to actually implement the localisation functionality into the directory.

**Comment by eriknson** [comment]
Agreed with @Mrtenz to put the entry point in the bottom right corner using the native (`<select>`) menu

<img width="1684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMktMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65042e9e6498712bb7e4ca20775e877a7ae496d1/Screenshot%202024-02-26%20at%2011.33.55.png" alt="Screenshot 2024-02-26 at 11.33.55.png" />
